# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c837ea70b4126fe26c95237e33d4b42987773daaf23932b325a77f1e2c8ce9be33ed3f32483e697c21e7199add45a87129ae7619ed804b298f0affcc0095ee92

test:
  secret_key_base: d70efa6653d0a12408f6dc6a41b542e04eddea5d2d300fc21607f269eece149dd007ba394878d682caceaa72c50004dbc7955469a8bf0f915342a1e19c5f6b18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
